#pragma once
#include "ui/debug/DebugSnapshotView.hpp"
#include <string>

/**
 * @brief Temporary console-based debug visualization layer (NOT final GUI).
 *
 * This renderer is experimental UI used for debugging purposes only.
 * It is NOT part of the final GUI architecture and will be replaced in the future
 * with a dedicated graphical interface (e.g. Dear ImGui / SDL2).
 *
 * The renderer operates exclusively on immutable simulation snapshots,
 * ensuring deterministic and side-effect-free visualization.
 *
 * @param view Immutable snapshot containing all data required for rendering.
 */
void renderView(const DebugSnapshotView& view);

/**
 * @brief Renders the UI header section.
 *
 * Displays simulation metadata such as tick count, execution mode,
 * number of robots, and snapshot index.
 *
 * @param view Snapshot containing grid and state data.
 */
void renderHeader(const DebugSnapshotView& view);

/**
 * @brief Renders the simulation grid.
 *
 * Displays the 2D world map including:
 * - Robots
 * - Static obstacles
 * - Dynamic obstacles
 * - Robot goals
 * - Planned path visualization (for selected robot)
 *
 * @param view Snapshot containing grid and state data.
 */
void renderGrid(const DebugSnapshotView& view);

/**
 * @brief Renders the UI footer with available debugger commands.
 *
 * Displays keyboard controls for interacting with the simulation:
 * next, back, run, pause, jump, select robot, quit.
 */
void renderFooter();

/**
 * @brief Converts an EventType enum into a human-readable string.
 *
 * @param type Event type generated by the simulation engine.
 * 
 * @return String representation of the event type.
 */
std::string eventTypeToString(EventType type);

/**
 * @brief Converts a RobotMode enum into a human-readable string.
 *
 * Represents the current lifecycle state of a robot.
 *
 * @param mode Robot mode.
 * 
 * @return String representation of the robot mode.
 */
std::string robotModeToString(RobotMode mode);

/**
 * @brief Renders robots and events side-by-side in the debug UI.
 *
 * Left column: robot states and positions
 * Right column: simulation events
 *
 * @param view Snapshot containing simulation state.
 */
void renderRobotsEventsSideBySide(const DebugSnapshotView& view);

/**
 * @brief Renders simulation timeline.
 *
 * Shows current tick progress relative to total simulation duration.
 *
 * @param view Snapshot containing current tick information.
 */
void renderTimeline(const DebugSnapshotView& view);

/**
 * @brief Renders performance metrics and inspector panel.
 *
 * Displays:
 * - Planner performance statistics
 * - Nodes expanded
 * - Execution time
 * - Selected robot inspector details
 *
 * @param view Snapshot containing performance and debug info.
 */
void renderPerfWithInspector(const DebugSnapshotView& view);