#pragma once
#include "ui/debug/DebugSnapshotView.hpp"  // Forward Declaration
#include <string>                          // For std::string

/**
 * @brief Renders the full debug snapshot to the console UI.
 *
 * This is the main entry point of the console-based debugger UI.
 *
 * @param view Immutable snapshot containing all data required for rendering.
 */
void renderView(const DebugSnapshotView& view);

/**
 * @brief Renders the UI header section.
 *
 * @param view Snapshot containing grid and state data.
 */
void renderHeader(const DebugSnapshotView& view);

/**
 * @brief Renders the simulation grid.
 *
 * Displays the 2D world map including:
 * - Robots
 * - Static obstacles
 * - Dynamic obstacles
 * - Robot goals
 *
 * @param view Snapshot containing grid and state data.
 */
void renderGrid(const DebugSnapshotView& view);

/**
 * @brief Renders a summary of all robots in the simulation.
 *
 * Shows per-robot information such as:
 * - Position
 * - Goal
 * - Current mode/state
 *
 * @param view Snapshot containing robot state data.
 */
void renderRobots(const DebugSnapshotView& view);

/**
 * @brief Renders all events generated in the current tick.
 *
 * Events include things like:
 * - Obstacle detection
 * - Collision avoidance
 * - Goal reached
 * - Replanning triggers
 *
 * @param view Snapshot containing event logs.
 */
void renderEvents(const DebugSnapshotView& view);

/**
 * @brief Renders the UI footer with available commands.
 *
 * Displays keyboard controls for interacting with the debugger:
 * next, back, run, pause, jump, quit.
 */
void renderFooter();

/**
 * @brief Converts an EventType enum value into a human-readable string.
 *
 * @param type The event type generated by the simulation engine.
 * 
 * @return String representation of the event type.
 */
std::string eventTypeToString(EventType type);

/**
 * @brief Converts a RobotMode enum value into a human-readable string.
 *
 * @param mode The current mode/state of a robot.
 * 
 * @return String representation of the robot mode.
 */
std::string robotModeToString(RobotMode mode);